INSERT INTO image (id, brand, name, description, img_src_path) VALUES (1, 'coke', 'Coke can', 'Coke can rendered by 3DS Max', 'assets/images/gallery/coke_1.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (2, 'sprite', 'Sprite bottle', 'Sprite bottle rendered by 3DS Max', 'assets/images/gallery/sprite_1.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (3, 'pepper', 'Dr Pepper cup', 'Dr Pepper cup rendered by 3DS Max', 'assets/images/gallery/pepper_1.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (4, 'coke', 'Coke can (top)', 'Coke can rendered by 3DS Max', 'assets/images/gallery/coke_2.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (5, 'coke', 'Coke can (bottom)', 'Coke can rendered by 3DS Max', 'assets/images/gallery/coke_3.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (6, 'coke', 'Coke can (left)', 'Coke can rendered by 3DS Max', 'assets/images/gallery/coke_4.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (7, 'coke', 'Coke can (right)', 'Coke can rendered by 3DS Max', 'assets/images/gallery/coke_5.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (8, 'coke', 'Coke can', 'Coke can rendered by 3DS Max using Arnold', 'assets/images/gallery/coke_6.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (9, 'sprite', 'Sprite bottle (top)', 'Sprite bottle rendered by 3DS Max', 'assets/images/gallery/sprite_2.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (10, 'sprite', 'Sprite bottle (bottom)', 'Sprite bottle rendered by 3DS Max', 'assets/images/gallery/sprite_3.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (11, 'sprite', 'Sprite bottle (left)', 'Sprite bottle rendered by 3DS Max', 'assets/images/gallery/sprite_4.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (12, 'sprite', 'Sprite bottle (right)', 'Sprite bottle rendered by 3DS Max', 'assets/images/gallery/sprite_5.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (13, 'sprite', 'Sprite bottle', 'Sprite bottle rendered by 3DS Max using Arnold', 'assets/images/gallery/sprite_6.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (14, 'pepper', 'Dr Pepper cup (top)', 'Dr Pepper cup rendered by 3DS Max', 'assets/images/gallery/pepper_2.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (15, 'pepper', 'Dr Pepper cup (bottom)', 'Dr Pepper cup rendered by 3DS Max', 'assets/images/gallery/pepper_3.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (16, 'pepper', 'Dr Pepper cup (left)', 'Dr Pepper cup rendered by 3DS Max', 'assets/images/gallery/pepper_4.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (17, 'pepper', 'Dr Pepper cup (right)', 'Dr Pepper cup rendered by 3DS Max', 'assets/images/gallery/pepper_5.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (18, 'pepper', 'Dr Pepper cup', 'Dr Pepper cup rendered by 3DS Max using Arnold', 'assets/images/gallery/pepper_6.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (19, 'fanta', 'Fanta can', 'Fanta can rendered by 3DS Max', 'assets/images/gallery/fanta_1.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (20, 'fanta', 'Fanta can (top)', 'Fanta can rendered by 3DS Max', 'assets/images/gallery/fanta_2.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (21, 'fanta', 'Fanta can (bottom)', 'Fanta can rendered by 3DS Max', 'assets/images/gallery/fanta_3.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (22, 'fanta', 'Fanta can (left)', 'Fanta can rendered by 3DS Max', 'assets/images/gallery/fanta_4.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (23, 'fanta', 'Fanta can (right)', 'Fanta can rendered by 3DS Max', 'assets/images/gallery/fanta_5.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (24, 'fanta', 'Fanta can', 'Fanta can rendered by 3DS Max using Arnold', 'assets/images/gallery/fanta_6.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (25, 'costa', 'Costa cup', 'Costa cup rendered by 3DS Max', 'assets/images/gallery/costa_1.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (26, 'costa', 'Costa cup (top)', 'Costa cup rendered by 3DS Max', 'assets/images/gallery/costa_2.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (27, 'costa', 'Costa cup (bottom)', 'Costa cup rendered by 3DS Max', 'assets/images/gallery/costa_3.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (28, 'costa', 'Costa cup (left)', 'Costa cup rendered by 3DS Max', 'assets/images/gallery/costa_4.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (29, 'costa', 'Costa cup (right)', 'Costa cup rendered by 3DS Max', 'assets/images/gallery/costa_5.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (30, 'costa', 'Costa cup', 'Costa cup rendered by 3DS Max using Arnold', 'assets/images/gallery/costa_6.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (31, 'appletizer', 'Appletizer bottle', 'Appletizer bottle rendered by 3DS Max', 'assets/images/gallery/appletizer_1.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (32, 'appletizer', 'Appletizer bottle (top)', 'Appletizer bottle rendered by 3DS Max', 'assets/images/gallery/appletizer_2.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (33, 'appletizer', 'Appletizer bottle (bottom)', 'Appletizer bottle rendered by 3DS Max', 'assets/images/gallery/appletizer_3.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (34, 'appletizer', 'Appletizer bottle (left)', 'Appletizer bottle rendered by 3DS Max', 'assets/images/gallery/appletizer_4.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (35, 'appletizer', 'Appletizer bottle (right)', 'Appletizer bottle rendered by 3DS Max', 'assets/images/gallery/appletizer_5.png');
INSERT INTO image (id, brand, name, description, img_src_path) VALUES (36, 'appletizer', 'Appletizer bottle', 'Appletizer bottle rendered by 3DS Max using Arnold', 'assets/images/gallery/appletizer_6.png');